# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "fixnames"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brent Sanders"]
  s.date = "2011-09-08"
  s.description = "Cleans up filenames so they can easily be used \nin scripts, without annoyances such as spaces or other bad characters "
  s.email = "git@thoughtnoise.net"
  s.executables = ["fixnames"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "fixnames.gemspec",
    "lib/fixnames.rb"
  ]
  s.homepage = "http://github.com/pdkl95/fixnames"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "filename cleanup for scripts"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<term-ansicolor>, ["~> 1.0.6"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<term-ansicolor>, ["~> 1.0.6"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<term-ansicolor>, ["~> 1.0.6"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

